#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-Warnings
Version  : 0.030
Release  : 40
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-Warnings-0.030.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-Warnings-0.030.tar.gz
Summary  : 'Test for warnings and the lack of them'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Test-Warnings-license = %{version}-%{release}
Requires: perl-Test-Warnings-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
This archive contains the distribution Test-Warnings,
version 0.030:
Test for warnings and the lack of them

%package dev
Summary: dev components for the perl-Test-Warnings package.
Group: Development
Provides: perl-Test-Warnings-devel = %{version}-%{release}
Requires: perl-Test-Warnings = %{version}-%{release}

%description dev
dev components for the perl-Test-Warnings package.


%package license
Summary: license components for the perl-Test-Warnings package.
Group: Default

%description license
license components for the perl-Test-Warnings package.


%package perl
Summary: perl components for the perl-Test-Warnings package.
Group: Default
Requires: perl-Test-Warnings = %{version}-%{release}

%description perl
perl components for the perl-Test-Warnings package.


%prep
%setup -q -n Test-Warnings-0.030
cd %{_builddir}/Test-Warnings-0.030

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test || :

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-Warnings
cp %{_builddir}/Test-Warnings-0.030/LICENCE %{buildroot}/usr/share/package-licenses/perl-Test-Warnings/69164988444003f1e2f00c57246af36c37320094
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::Warnings.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Test-Warnings/69164988444003f1e2f00c57246af36c37320094

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.30.3/Test/Warnings.pm
